export const tvlData = [
    { name: 'Jan', tvl: 4000 },
    { name: 'Feb', tvl: 3000 },
    { name: 'Mar', tvl: 5000 },
    { name: 'Apr', tvl: 2780 },
    { name: 'May', tvl: 1890 },
    { name: 'Jun', tvl: 2390 },
    { name: 'Jul', tvl: 3490 },
];

export const projects = [
    {
        id: "1",
        name: 'UniDex',
        description: 'Decentralized exchange aggregator with advanced trading features.',
        logo: '/projects/image.png',
        verified: true,
        tags: ['DeFi', 'DEX', 'Aggregator'],
        tvl: 1000000,
        users24h: 5000,
        totalQuests: 10,
        activeQuests: true,
        category: 'DeFi',
        bannerImage: 'https://picsum.photos/1200/400',
        founder: 'UniDex Team',
        founderAvatar: 'https://picsum.photos/40/40',
        website: 'https://unidex.exchange',
        github: 'https://github.com/unidex',
        twitter: 'https://twitter.com/unidexexchange',
        contractAddress: '0x1234...5678',
        dailyActiveUsers: 15000,
        totalPointsAllocated: 100000,
        questCompletionRate: 75,
    },
    {
        id: "2",
        name: 'Project 2',
        description: 'Description of Project 2',
        logo: 'https://picsum.photos/48/48',
        verified: false,
        tags: ['GameFi', 'NFT'],
        tvl: 1000000,
        users24h: 5000,
        totalQuests: 10,
        activeQuests: true,
        category: 'GameFi',
        bannerImage: 'https://picsum.photos/1200/400',
        founder: 'Project 2 Team',
        founderAvatar: 'https://picsum.photos/40/40',
        website: 'https://project2.com',
        github: 'https://github.com/project2',
        twitter: 'https://twitter.com/project2',
        contractAddress: '0x1234...5678',
        dailyActiveUsers: 15000,
        totalPointsAllocated: 100000,
        questCompletionRate: 75,
    },
    {
        id: "3",
        name: 'Project 3',
        description: 'Description of Project 3',
        logo: 'https://picsum.photos/48/48',
        verified: false,
        tags: ['GameFi', 'NFT'],
        tvl: 1000000,
        users24h: 5000,
        totalQuests: 10,
        activeQuests: true,
        category: 'NFT',
        bannerImage: 'https://picsum.photos/1200/400',
        founder: 'Project 3 Team',
        founderAvatar: 'https://picsum.photos/40/40',
        website: 'https://project3.com',
        github: 'https://github.com/project3',
        twitter: 'https://twitter.com/project3',
        contractAddress: '0x1234...5678',
        dailyActiveUsers: 15000,
        totalPointsAllocated: 100000,
        questCompletionRate: 75,
    },
];